### ISSUE TITLE
Part Time Course - Week 3

### ISSUE THREAD

**Issue by RanaAlqrenawi** [gazaskygeeks/shecodes#6]
Guys, it would be great if you start producing new readme for week 3 for this Thursday like what @eliascodes has done in the first 2 weeks. The reference in the FAC repo is your resource. :v: 

@mhmdshorafa @mohanagy @Alaa-Khattab

**Comment by RanaAlqrenawi** [comment]
@eliascodes uh, sorry! I've just noticed that you wrote a comment for the same thing here: https://github.com/foundersandcoders/gaza-programme/issues/16

So, @mhmdshorafa @mohanagy @Alaa-Khattab guys, check the above comment from Elias clarifying the stuff! :v:

**Comment by eliasmalik** [comment]
This was done in #7
