### ISSUE TITLE
Week 4 readme

### ISSUE THREAD

**Issue by RanaAlqrenawi** [gazaskygeeks/shecodes#9]
@abeeralshaer @shahenazmonia Are we expecting from you the readme for the last week after you've done from it tomorrow before we jump to work on week 5 with @mhmdshorafa @mohanagy and @Alaa-Khattab ? cc: @eliascodes @saralk

**Comment by abeeralshaer** [comment]
it's up their !  @RanaAlqrenawi @eliascodes @saralk 
week got too hectic but don't worry :+1:
